name: home_-_particles
timestamp: 1489282221
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1489282176
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  custom:
    custom-5807: Intro
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  logo:
    logo-5864: 'Logo / Image'
    logo-8467: 'Logo / Image'
  menu:
    menu-8537: Menu
  social:
    social-2792: Social
  copyright:
    copyright-7095: Copyright
  horizontalmenu:
    horizontalmenu-9963: 'Horizontal Menu'
  totop:
    totop-2780: 'To Top'
  mobile-menu:
    mobile-menu-1413: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-5864: logo-9608
    menu-8537: menu-6409
    social-2792: social-3171
    logo-8467: logo-9571
    copyright-7095: copyright-1736
    horizontalmenu-9963: horizontalmenu-9034
    totop-2780: totop-8670
    mobile-menu-1413: mobile-menu-5697
